example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog')
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_watchlist,show_json,show_xml,show_json_by_id


app_name = 'mywatchlist'

urlpatterns = [path('', show_watchlist, name='show_watchlist'),
    path('html/', show_watchlist, name='show_watchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/<int:id>', show_json_by_id, name= 'show_json_by_id'),
    path('json/', show_json, name='show_json_by_id'),
    ]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
# TODO: Implement Routings Herefrom django.urls import path
from todolist.views import show_todolist, set_remove,set_status,register,login_user,logout_user,new_task,show_json,show_todolist_ajax
from django.urls import path

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', new_task, name='new_task'),
    path("set_remove/<int:id>", set_remove, name="set_remove"),
    path("set_status/<int:id>", set_status, name="set_status"),
    path('json/', show_json, name='show_json'),
    path('ajax/', show_todolist_ajax, name='show_todolist_ajax'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class watchlistItems(models.Model):
    watched = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    rating = models.IntegerField()
    release_date = models.CharField(max_length=255)
    review = models.TextField()

todolist/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    date = models.TextField()
    title = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default=False)
    status = models.TextField

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_katalog(request):
    data_katalog_item = CatalogItem.objects.all()
    context = {
        'list_item': data_katalog_item,
        'name': 'Muhammad Ghazian Gunawan',
        'student_id': '2106656522'
    }
    return render(request, 'katalog.html',context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import watchlistItems
from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def show_watchlist(request):
    data_watchlist_item = watchlistItems.objects.all()
    context = {
        'list_item': data_watchlist_item,
        'name': 'Muhammad Ghazian Gunawan',
        'student_id': '2106656522'
    }

    return render(request, 'watchlist.html',context)



def show_xml(request):
    data = watchlistItems.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = watchlistItems.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")
    

def show_json_by_id(request, id):
    data = watchlistItems.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from todolist.models import Task
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

@login_required(login_url="/todolist/login/")
def set_status(request, id):
    item = Task.objects.get(user=request.user, id=id)
    item.is_finished = not item.is_finished
    item.save(update_fields=["is_finished"])
    return HttpResponseRedirect(reverse("todolist:show_todolist"))


@login_required(login_url="/todolist/login/")
def set_remove(request, id):
    item = Task.objects.get(user=request.user, id=id)
    item.delete()
    return HttpResponseRedirect(reverse("todolist:show_todolist"))

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_todolist_item = Task.objects.filter(user=request.user)
    context = {"list_item": data_todolist_item, "username": str(request.user).upper(),"user_id" : request.user.id}   
    return render(request, 'todolist.html',context)

@login_required(login_url='/todolist/login/')
def show_todolist_ajax(request):
    data_todolist_item = Task.objects.filter(user=request.user)
    context = {"list_item": data_todolist_item, "username": str(request.user).upper(),"user_id" : request.user.id}   
    return render(request, 'todolist_ajax.html',context)

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account successfully created!')
            return redirect('todolist:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # create response
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Wrong Username or Password!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def new_task(request):
    if request.method == 'POST':
        response = HttpResponseRedirect(reverse('todolist:show_todolist'))
        Task.objects.create(user = request.user,date = datetime.datetime.now(),title = request.POST.get('title'),description = request.POST.get('description'),)
        return response
    context = {"username": str(request.user).upper()}
    return render(request, 'new_task.html',context)

@login_required(login_url="/todolist/login/")
def show_json(request):
    data = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/todolist/login/')
def new_task_ajax(request):
    if request.method == "POST":
        response =  JsonResponse({"instance": "Task Created"},status=200)
        new_task = Task.objects.create(user = request.user,date = datetime.datetime.now(),title = request.POST.get('title'),description = request.POST.get('description'),)
        new_task.save()
        return response
    

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Assignment 2 PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{name}}</p>

  <h5>Student ID: </h5>
  <p>{{student_id}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% comment %} Add data below {% endcomment %}
    {% for item in list_item %}
        <tr>
            <th>{{item.item_name}}</th>
            <th>{{item.item_price}}</th>
            <th>{{item.item_stock}}</th>
            <th>{{item.rating}}</th>
            <th>{{item.description}}</th>
            <th>{{item.item_url}}</th>
        </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/watchlist.html
{% extends 'base.html' %}

{% block content %}
<style>
    tr:nth-child(even) {background-color: #bbbbbb;}
    th {
  background-color: #060c80;
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: middle;
  color: white;
  font-family: Arial, Helvetica, sans-serif;
}
    td{
        color: black;
        font-family: Arial, Helvetica, sans-serif;
    }
    h1,h5,p{
        text-align: center;
        font-family: Arial, Helvetica, sans-serif;
    }
</style>
    <h1>Assignment 3 PBP/PBD</h1>
    <h5>Name: </h5>
    <p>{{name}}</p>
    <h5>Student ID: </h5>
    <p>{{student_id}}</p>


<table >
    <tr>
    <th>Watched</th>
    <th>Title</th>
    <th>Rating</th>
    <th>Release Date</th>
    <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in list_item %}
    <tr>
        <td>{{item.watched}}</td>
        <td>{{item.title}}</td>
        <td>{{item.rating}}</td>
        <td>{{item.release_date}}</td>
        <td>{{item.review}}</td>
    </tr>
    {% endfor %}
</table>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>

</html>

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<style>
    .navbar-text{
      color:#ffffff;
      font-weight:bold;
      font-size:150%
    }
    th,td{
      color:#ffffff
    }
    .navbar-custom {
      background-color: #373C3F ;
    }
    .nav-link{
      color: #fffc
    }
    h1{
        text-align:center;
        color:white;
    }
    .global-container{
        height: 100%;
        display: flex;
        align-items:center;
        justify-content:center;
        color: #ffffff;
    }
    .card-title{
        color: #ffffff
    }
    .login-form{
        width: 380px;
        height:450px;
        padding: 20px;
        background-color: #2F3438 ; 
        border-radius:10px;
    }
    body{
        background-image: url(https://wallpaperaccess.com/full/7237875.png)
    }
    </style>

<nav class="navbar  navbar-expand-lg navbar-dark bg-dark navbar-brand-center py-3">
    <div class="container-fluid">
        <a class="navbar-brand mb-0 h1 " href="#"><img src="https://www.iconsdb.com/icons/preview/white/checkmark-xxl.png" width="50" height="50"></a>
    </div>
</nav>

<body>
    <div class="global-container mt-5 ">
        <div class="card login-form">
            <div class="card-body">
                <h1 class="card-title text-center">
                    Login
                </h1>
                <div class="card-text">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="container">
                            <div class="row mt-5 mb-2">
                                    <tr>
                                        <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                                    </tr>
                                </div>   
                                <div class="row mb-5">
                                    <tr>
                                        <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                                    </tr>
                                </div>
                                <div class="row mb-3">
                                    <tr>
                                        <td><button type="submit" class="btn btn-primary">Submit</button></td>
                                    </tr>
                                </div>
                                <div class="row">
                                    <tr>
                                        <br><td>Don't have an account?</td> <br><a href="{% url 'todolist:register' %}">Create Account</a>
                                    </tr> 
                                </div>
                                <div class="row">
                                    <tr>
                                    {% if messages %}
                                        <ul>
                                            {% for message in messages %}
                                                <li>{{ message }}</li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                    </tr>
                                </div>
                        </div>
                    </form>
                </body>
                </div>
            </div>
        </div>
</div>

{% endblock content %}

todolist/templates/new_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create New Task</title>
{% endblock meta %}

{% block content %}
<style>
  .navbar-text{
    color:rgb(255, 186, 12);
    font-weight:bold;
    font-size:150%
  }
  th,td{
    color:#ffffff
  }
  .navbar-custom {
    background-color: #373C3F ;
  }
  .nav-link{
    color: #fff
  }
  h1{
      text-align:center;
      color:white;
  }
  .global-container{
      height: 100%;
      display: flex;
      align-items:center;
      justify-content:center;
      color: #ffffff;
  }
  .card-title{
      color: #ffffff
  }
  .login-form{
      width: 380px;
      height:450px;
      padding: 20px;
      background-color: #2F3438 ; 
      border-radius:10px;
  }
  </style>

  <nav class="navbar  navbar-expand-lg navbar-dark bg-dark py-3">
    <div class="container-fluid">
      <a class="navbar-brand mb-0 h1" href="{% url 'todolist:show_todolist' %}"><img src="https://www.iconsdb.com/icons/preview/white/checkmark-xxl.png" width="50" height="50"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle Navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav" me-auto mb-2 mb-lg-0 >
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:logout' %}">Logout</a>
          </li>
        </ul>
      </div>
      <span class="navbar-text">
        Hello {{username}} 👋
      </span>
    </div>
  </nav>

<body style="background-image: url(https://wallpaperaccess.com/full/7237875.png) ">
  <div class="global-container mt-5 ">
      <div class="card login-form">
          <div class="card-body">
              <h1 class="card-title text-center">
                  Add New Task
              </h1>
              <div class="card-text">
                  <form method="POST" action="">
                      {% csrf_token %}
                      <div class="container">
                          <div class="row mt-5 mb-2">
                            <tr>
                              <td>Task Title</td>
                              <td><input type="text" name="title" placeholder="Enter Task Title" class="form-control"></td>
                            </tr>
                              </div>   
                              <div class="row mb-5">
                                <tr>
                                  <td>Task Description</td>
                                  <td><input type="text" name="description" placeholder="Enter Task Description" class="form-control"></td>
                              </tr>
                              </div>
                              <div class="row mb-3">
                                  <tr>
                                      <td><button type="submit" class="btn btn-primary">Submit</button></td>
                                  </tr>
                              </div>
                      </div>
                  </form>
              </body>
              </div>
          </div>
      </div>
</div>





{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block content %}
<style>
    .navbar-text{
      color:#ffffff;
      font-weight:bold;
      font-size:150%
    }
    th,td{
      color:#ffffff
    }
    .navbar-custom {
      background-color: #373C3F ;
    }
    .nav-link{
      color: #fff
    }
    h1{
        text-align:center;
        color:white;
    }
    .global-container{
        height: 100%;
        display: flex;
        align-items:center;
        justify-content:center;
        color: #ffffff;
    }
    .card-title{
        color: #ffffff
    }
    .login-form{
        width: 500px;
        height:800;
        padding: 20px;
        background-color: #2F3438 ; 
        border-radius:10px;
    }
    </style>

<nav class="navbar  navbar-expand-lg navbar-dark bg-dark navbar-brand-center py-3">
    <div class="container-fluid">
        <a class="navbar-brand mb-0 h1 " href="#"><img src="https://www.iconsdb.com/icons/preview/white/checkmark-xxl.png" width="50" height="50"></a>
    </div>
</nav>

<body style="background-image: url(https://wallpaperaccess.com/full/7237875.png) ">
    <div class="global-container mt-5 ">
        <div class="card login-form">
            <div class="card-body">
                <h1 class="card-title text-center">
                    Registration
                </h1>
                <div class="card-text">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="container">
                            <div class="row mt-5 mb-2">
                                    <tr>
                                        <form method="POST" >
                                            {% csrf_token %}
                                            <table>
                                                {{ form.as_table }}
                                                <tr>
                                                    <td></td>
                                                    <td><input type="submit" name="submit" value="Register"/></td>
                                                </tr>
                                            </table>
                                        </form>
                                    </tr>
                                </div>   
                                <div class="row">
                                    <tr>
                                    {% if messages %}
                                        <ul>
                                            {% for message in messages %}
                                                <li>{{ message }}</li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                    </tr>
                                </div>
                        </div>
                    </form>
                </body>
                </div>
            </div>
        </div>
</div>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}
{% block content %}

<style>
  .navbar-text{
    color:#ffffff;
    font-weight:bold;
    font-size:150%
  }
  th,td{
    color:#ffffff
  }
  .navbar-custom {
    background-color: #373C3F ;
  }
  .nav-link{
    color: #fff
  }
  .card-header,.card-title,.card-text{
    color: #ffffff
  }
  .card:hover{
  transform: scale(1.02);
  box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
}


</style>

<nav class="navbar  navbar-expand-lg navbar-custom py-3">
    <div class="container-fluid">
      <a class="navbar-brand mb-0 h1" href="{% url 'todolist:show_todolist' %}"><img src="https://www.iconsdb.com/icons/preview/white/checkmark-xxl.png" width="50" height="50"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle Navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav" me-auto mb-2 mb-lg-0 >
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:logout' %}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:new_task' %}">Add Task</a>
          </li>
        </ul>
      </div>
      <span class="navbar-text">
        Hello {{username}} 👋
      </span>
    </div>
  </nav>


<body style="background-color:#2F3438 ">
    {% for item in list_item %}
    <tr>
      <div class="card bg-secondary hover-shadow mb-2 mt-5" >
        <div class="card-header">
          <th>{{item.title}}{% if item.is_finished %}
            ✅
            {% else %} 
            ❌
            {% endif %}
          </th>
        </div>
        <div class="card-body">
          <h5 class="card-title">{{item.date}}</h5>
          <p class="card-text">{{item.description}}</p>
          <button type="button" class="btn btn-primary"><a href="{% url 'todolist:set_status' item.id %}"style="color:#ffffff; text-decoration: none;">set status</a></button>
          <button type="button" class="btn btn-warning"><a href="{% url 'todolist:set_remove' item.id %}"style="color:#ffffff; text-decoration: none;">Remove Task</a></button>
        </div>
      </div>
            
        </th>
        {% endfor %}
      </tr>
</body>
{% endblock content %}

todolist/templates/todolist_ajax.html
{% extends 'base.html' %}
{% block content %}

<style>
  .navbar-text{
    color:#ffffff;
    font-weight:bold;
    font-size:150%
  }
  th,td{
    color:#ffffff
  }
  .navbar-custom {
    background-color: #373C3F ;
  }
  .nav-link{
    color: #fff
  }
  .card-header,.card-title,.card-text{
    color: #ffffff
  }
  .card:hover{
  transform: scale(1.02);
  box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
}


</style>

<nav class="navbar  navbar-expand-lg navbar-custom py-3">
    <div class="container-fluid">
      <a class="navbar-brand mb-0 h1" href="{% url 'todolist:show_todolist' %}"><img src="https://www.iconsdb.com/icons/preview/white/checkmark-xxl.png" width="50" height="50"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle Navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav" me-auto mb-2 mb-lg-0 >
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:logout' %}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:new_task' %}">Add Task</a>
          </li>
        </ul>
      </div>
      <span class="navbar-text">
        Hello {{username}} 👋
      </span>
    </div>
  </nav>

  <div class="col">
<body style="background-color:#2F3438 ">
  <div class="row" id="table">
  
  </div>
  <br>  
  </body>   


  <script>
    $(document).ready(function() {
    function card(task) {
        return `
        <tr>
      <div class="card bg-secondary hover-shadow mb-2 mt-5" >
        <div class="card-header">
          <th>${task.fields.title}
            ${task.fields.is_finished ? "✅" : "❌"}
          </th>
        </div>
        <div class="card-body">
          <h5 class="card-title">${task.fields.date}</h5>
          <p class="card-text">${task.fields.description}</p>
          <input type="submit" value="Change Status" class="status" onclick="change_status(${task.pk})" />
          <input type="submit" value="Delete Task"  class="status" onclick="delete_task(${ task.pk })" />
        </div>
      </div>
            
        </th>
        `
    };
    function loop() {
        $.get("{% url 'todolist:show_json' %}", function(data) {
            $.each(data, function(i, value) {
                $("#container0").append(card(value));
            });
        });
    };
    loop();

{%endblock content%}